"""Distinct persistence models for installed quotation and inventory packs."""
from datetime import datetime
from uuid import uuid4
from sqlalchemy import DateTime, ForeignKey, Integer, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from packages.database.db import Base

def uid():return str(uuid4())

class QuoteCustomer(Base):
    __tablename__="quote_customers";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);project_id:Mapped[str]=mapped_column(ForeignKey("generated_projects.id"),index=True);name:Mapped[str]=mapped_column(String(160));email:Mapped[str]=mapped_column(String(320));created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Inquiry(Base):
    __tablename__="quote_inquiries";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);project_id:Mapped[str]=mapped_column(ForeignKey("generated_projects.id"),index=True);customer_id:Mapped[str]=mapped_column(ForeignKey("quote_customers.id"));reference:Mapped[str]=mapped_column(String(24),unique=True);idempotency_key:Mapped[str]=mapped_column(String(120));requirements:Mapped[str]=mapped_column(Text);status:Mapped[str]=mapped_column(String(30),default="inquiry_received");version:Mapped[int]=mapped_column(Integer,default=1);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);__table_args__=(UniqueConstraint("tenant_id","project_id","idempotency_key",name="uq_quote_inquiry_idempotency"),)
class Quotation(Base):
    __tablename__="quotations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);project_id:Mapped[str]=mapped_column(ForeignKey("generated_projects.id"),index=True);inquiry_id:Mapped[str]=mapped_column(ForeignKey("quote_inquiries.id"));status:Mapped[str]=mapped_column(String(30),default="quotation_draft");current_version:Mapped[int]=mapped_column(Integer,default=1);version:Mapped[int]=mapped_column(Integer,default=1);public_token:Mapped[str|None]=mapped_column(String(120),nullable=True,unique=True);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class QuotationVersion(Base):
    __tablename__="quotation_versions";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);quotation_id:Mapped[str]=mapped_column(ForeignKey("quotations.id",ondelete="CASCADE"));number:Mapped[int]=mapped_column(Integer);deliverable:Mapped[str]=mapped_column(Text,default="");total:Mapped[float]=mapped_column(Numeric(12,2),default=0);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);__table_args__=(UniqueConstraint("quotation_id","number",name="uq_quotation_version"),)
class QuotationLineItem(Base):
    __tablename__="quotation_line_items";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);version_id:Mapped[str]=mapped_column(ForeignKey("quotation_versions.id",ondelete="CASCADE"));description:Mapped[str]=mapped_column(String(500));quantity:Mapped[int]=mapped_column(Integer);unit_price:Mapped[float]=mapped_column(Numeric(12,2))
class QuotationApproval(Base):
    __tablename__="quotation_approvals";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);quotation_id:Mapped[str]=mapped_column(ForeignKey("quotations.id",ondelete="CASCADE"));status:Mapped[str]=mapped_column(String(20),default="pending");actor_id:Mapped[str|None]=mapped_column(String(36),nullable=True);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class QuotationStatusEvent(Base):
    __tablename__="quotation_status_events";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);quotation_id:Mapped[str]=mapped_column(ForeignKey("quotations.id",ondelete="CASCADE"));from_status:Mapped[str|None]=mapped_column(String(30),nullable=True);to_status:Mapped[str]=mapped_column(String(30));actor_id:Mapped[str|None]=mapped_column(String(36),nullable=True);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)

class Product(Base):
    __tablename__="inventory_products";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);project_id:Mapped[str]=mapped_column(ForeignKey("generated_projects.id"),index=True);sku:Mapped[str]=mapped_column(String(80));name:Mapped[str]=mapped_column(String(200));unit_cost:Mapped[float]=mapped_column(Numeric(12,2),default=0);reorder_point:Mapped[int]=mapped_column(Integer,default=0);version:Mapped[int]=mapped_column(Integer,default=1);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);__table_args__=(UniqueConstraint("tenant_id","project_id","sku",name="uq_inventory_product_sku"),)
class Supplier(Base):
    __tablename__="inventory_suppliers";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);project_id:Mapped[str]=mapped_column(ForeignKey("generated_projects.id"),index=True);name:Mapped[str]=mapped_column(String(200));email:Mapped[str|None]=mapped_column(String(320),nullable=True)
class InventoryLocation(Base):
    __tablename__="inventory_locations";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);project_id:Mapped[str]=mapped_column(ForeignKey("generated_projects.id"),index=True);name:Mapped[str]=mapped_column(String(200))
class StockLevel(Base):
    __tablename__="inventory_stock_levels";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);product_id:Mapped[str]=mapped_column(ForeignKey("inventory_products.id"));location_id:Mapped[str]=mapped_column(ForeignKey("inventory_locations.id"));quantity:Mapped[int]=mapped_column(Integer,default=0);version:Mapped[int]=mapped_column(Integer,default=1);__table_args__=(UniqueConstraint("tenant_id","product_id","location_id",name="uq_inventory_stock_level"),)
class StockMovement(Base):
    __tablename__="inventory_stock_movements";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);product_id:Mapped[str]=mapped_column(ForeignKey("inventory_products.id"));location_id:Mapped[str]=mapped_column(ForeignKey("inventory_locations.id"));movement_type:Mapped[str]=mapped_column(String(30));quantity_delta:Mapped[int]=mapped_column(Integer);reference:Mapped[str]=mapped_column(String(120),default="");actor_id:Mapped[str]=mapped_column(String(36));created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class PurchaseOrder(Base):
    __tablename__="inventory_purchase_orders";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);project_id:Mapped[str]=mapped_column(ForeignKey("generated_projects.id"),index=True);supplier_id:Mapped[str]=mapped_column(ForeignKey("inventory_suppliers.id"));status:Mapped[str]=mapped_column(String(30),default="draft");version:Mapped[int]=mapped_column(Integer,default=1);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class PurchaseOrderLine(Base):
    __tablename__="inventory_purchase_order_lines";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);purchase_order_id:Mapped[str]=mapped_column(ForeignKey("inventory_purchase_orders.id",ondelete="CASCADE"));product_id:Mapped[str]=mapped_column(ForeignKey("inventory_products.id"));ordered_quantity:Mapped[int]=mapped_column(Integer);received_quantity:Mapped[int]=mapped_column(Integer,default=0);unit_cost:Mapped[float]=mapped_column(Numeric(12,2))
class ReorderRule(Base):
    __tablename__="inventory_reorder_rules";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);product_id:Mapped[str]=mapped_column(ForeignKey("inventory_products.id"));location_id:Mapped[str]=mapped_column(ForeignKey("inventory_locations.id"));minimum_quantity:Mapped[int]=mapped_column(Integer);reorder_quantity:Mapped[int]=mapped_column(Integer)
