from datetime import datetime
from uuid import uuid4

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, String, Text, event
from sqlalchemy.orm import Mapped, mapped_column

from packages.database.db import Base


def uid() -> str:
    return str(uuid4())


# Correlation IDs are generated by Operly and remain UUID-shaped today. Causation
# IDs cross provider/runtime boundaries and may be OpenAI/Groq/Anthropic/MCP tool
# call identifiers, so they must not be constrained to UUID width.
TRACE_ID_LENGTH = 160


class BusinessEventRecord(Base):
    __tablename__ = "business_events"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=uid)
    scope_kind: Mapped[str] = mapped_column(String(20), default="workspace", nullable=False, index=True)
    tenant_id: Mapped[str | None] = mapped_column(ForeignKey("tenants.id"), nullable=True, index=True)
    owner_user_id: Mapped[str | None] = mapped_column(
        ForeignKey("app_users.id", ondelete="CASCADE"), nullable=True, index=True
    )
    event_type: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    occurred_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    actor_type: Mapped[str] = mapped_column(String(40), default="system", nullable=False)
    actor_id: Mapped[str | None] = mapped_column(String(120), nullable=True)
    source: Mapped[str] = mapped_column(String(100), default="operly", nullable=False)
    payload_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    correlation_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    causation_id: Mapped[str | None] = mapped_column(String(TRACE_ID_LENGTH), nullable=True)
    metadata_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    __table_args__ = (
        CheckConstraint(
            "(scope_kind = 'workspace' AND tenant_id IS NOT NULL AND owner_user_id IS NULL) OR "
            "(scope_kind = 'personal' AND tenant_id IS NULL AND owner_user_id IS NOT NULL)",
            name="ck_business_events_scope_owner",
        ),
        Index("ix_business_events_tenant_type_time", "tenant_id", "event_type", "occurred_at"),
        Index("ix_business_events_owner_type_time", "owner_user_id", "event_type", "occurred_at"),
    )


class BusinessActionRecord(Base):
    __tablename__ = "business_actions"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=uid)
    scope_kind: Mapped[str] = mapped_column(String(20), default="workspace", nullable=False, index=True)
    tenant_id: Mapped[str | None] = mapped_column(ForeignKey("tenants.id"), nullable=True, index=True)
    owner_user_id: Mapped[str | None] = mapped_column(
        ForeignKey("app_users.id", ondelete="CASCADE"), nullable=True, index=True
    )
    objective: Mapped[str] = mapped_column(Text, nullable=False)
    capability: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    provider: Mapped[str | None] = mapped_column(String(100), nullable=True)
    arguments_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    rationale: Mapped[str] = mapped_column(Text, default="", nullable=False)
    expected_outcome: Mapped[str] = mapped_column(Text, default="", nullable=False)
    risk_level: Mapped[str] = mapped_column(String(30), default="low", nullable=False)
    status: Mapped[str] = mapped_column(String(40), default="PROPOSED", nullable=False, index=True)
    policy_decision: Mapped[str | None] = mapped_column(String(30), nullable=True)
    approval_id: Mapped[str | None] = mapped_column(ForeignKey("approvals.id"), nullable=True, index=True)
    result_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    verification_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    correlation_id: Mapped[str] = mapped_column(String(36), default=uid, nullable=False, index=True)
    causation_id: Mapped[str | None] = mapped_column(String(TRACE_ID_LENGTH), nullable=True, index=True)
    idempotency_key: Mapped[str | None] = mapped_column(String(160), nullable=True, index=True)
    approved_arguments_digest: Mapped[str | None] = mapped_column(String(64), nullable=True)
    principal_id: Mapped[str | None] = mapped_column(String(120), nullable=True, index=True)
    client_id: Mapped[str | None] = mapped_column(String(120), nullable=True, index=True)
    origin: Mapped[str | None] = mapped_column(String(40), nullable=True, index=True)
    connector_id: Mapped[str | None] = mapped_column(String(120), nullable=True, index=True)
    resource_type: Mapped[str | None] = mapped_column(String(80), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    __table_args__ = (
        CheckConstraint(
            "(scope_kind = 'workspace' AND tenant_id IS NOT NULL AND owner_user_id IS NULL) OR "
            "(scope_kind = 'personal' AND tenant_id IS NULL AND owner_user_id IS NOT NULL)",
            name="ck_business_actions_scope_owner",
        ),
        Index("ix_business_actions_owner_status", "owner_user_id", "status", "created_at"),
    )


@event.listens_for(BusinessEventRecord, "before_update")
@event.listens_for(BusinessEventRecord, "before_delete")
def _immutable_business_event(mapper, connection, target):
    del mapper, connection, target
    raise ValueError("Business events are append-only and immutable")
