from datetime import datetime
from uuid import uuid4
from sqlalchemy import Boolean,DateTime,Float,ForeignKey,Integer,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from packages.database.db import Base

def uid():return str(uuid4())

class PaymentRecord(Base):
 __tablename__="payment_records"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True)
 kind:Mapped[str]=mapped_column(String(40));provider:Mapped[str]=mapped_column(String(60));provider_id:Mapped[str]=mapped_column(String(200));status:Mapped[str]=mapped_column(String(50));amount:Mapped[float]=mapped_column(Float,default=0);currency:Mapped[str]=mapped_column(String(3),default="usd");customer_email:Mapped[str|None]=mapped_column(String(320),nullable=True);description:Mapped[str]=mapped_column(Text,default="");url:Mapped[str|None]=mapped_column(Text,nullable=True);metadata_json:Mapped[str]=mapped_column(Text,default="{}");created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
 __table_args__=(UniqueConstraint("tenant_id","provider","provider_id",name="uq_payment_provider_id"),)

class CustomPluginRecord(Base):
 __tablename__="custom_plugins"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True);plugin_id:Mapped[str]=mapped_column(String(100));display_name:Mapped[str]=mapped_column(String(200));description:Mapped[str]=mapped_column(Text,default="");base_url:Mapped[str]=mapped_column(Text);allowed_domain:Mapped[str]=mapped_column(String(255));auth_type:Mapped[str]=mapped_column(String(30),default="none");credential_reference:Mapped[str|None]=mapped_column(ForeignKey("connector_secrets.id"),nullable=True);capabilities_json:Mapped[str]=mapped_column(Text,default="[]");status:Mapped[str]=mapped_column(String(40),default="proposed");enabled:Mapped[bool]=mapped_column(Boolean,default=False);test_results_json:Mapped[str]=mapped_column(Text,default="{}");created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
 __table_args__=(UniqueConstraint("tenant_id","plugin_id",name="uq_custom_plugin_tenant_id"),)

class CompanyProfile(Base):
 __tablename__="company_profiles"
 tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),primary_key=True);answers_json:Mapped[str]=mapped_column(Text,default="{}");profile_json:Mapped[str]=mapped_column(Text,default="{}");field_meta_json:Mapped[str]=mapped_column(Text,default="{}");completed_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True);updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)

class CompanyEvidence(Base):
 __tablename__="company_evidence"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),nullable=False,index=True);field_key:Mapped[str]=mapped_column(String(120),nullable=False,index=True);value_json:Mapped[str]=mapped_column(Text,nullable=False);source_type:Mapped[str]=mapped_column(String(40),nullable=False);source_url:Mapped[str|None]=mapped_column(Text,nullable=True);source_reference:Mapped[str|None]=mapped_column(String(255),nullable=True);confidence:Mapped[float]=mapped_column(Float,default=0.5);observed_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,index=True);owner_confirmed:Mapped[bool]=mapped_column(Boolean,default=False);superseded:Mapped[bool]=mapped_column(Boolean,default=False);stale:Mapped[bool]=mapped_column(Boolean,default=False);content_hash:Mapped[str]=mapped_column(String(64),nullable=False)
 __table_args__=(UniqueConstraint("tenant_id","field_key","content_hash","source_type",name="uq_company_evidence_fact"),)

class CompanyQuestion(Base):
 __tablename__="company_questions"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),nullable=False,index=True);question:Mapped[str]=mapped_column(Text,nullable=False);why_it_matters:Mapped[str]=mapped_column(Text,nullable=False);target_fields_json:Mapped[str]=mapped_column(Text,nullable=False);business_type:Mapped[str|None]=mapped_column(String(80),nullable=True);answered:Mapped[bool]=mapped_column(Boolean,default=False,index=True);answer_json:Mapped[str|None]=mapped_column(Text,nullable=True);owner_confirmed:Mapped[bool]=mapped_column(Boolean,default=False);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);answered_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True)

class CompanyResearchRun(Base):
 __tablename__="company_research_runs"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),nullable=False,index=True);seed:Mapped[str]=mapped_column(Text,nullable=False);status:Mapped[str]=mapped_column(String(30),default="running",index=True);searches_used:Mapped[float]=mapped_column(Float,default=0);pages_used:Mapped[float]=mapped_column(Float,default=0);completion_reason:Mapped[str|None]=mapped_column(String(120),nullable=True);summary_json:Mapped[str]=mapped_column(Text,default="{}");started_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);completed_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True)

class SolutionRecord(Base):
 __tablename__="solutions"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),nullable=False,index=True);name:Mapped[str]=mapped_column(String(200),nullable=False);description:Mapped[str]=mapped_column(Text,default="");solution_type:Mapped[str]=mapped_column(String(60),nullable=False,index=True);lifecycle_status:Mapped[str]=mapped_column(String(30),nullable=False,index=True);runtime_type:Mapped[str]=mapped_column(String(40),nullable=False);runtime_reference:Mapped[str]=mapped_column(String(120),nullable=False);current_version_reference:Mapped[str|None]=mapped_column(String(120),nullable=True);preview_state:Mapped[str]=mapped_column(String(30),default="unavailable");preview_url:Mapped[str|None]=mapped_column(Text,nullable=True);production_state:Mapped[str]=mapped_column(String(30),default="offline");production_url:Mapped[str|None]=mapped_column(Text,nullable=True);visibility:Mapped[str]=mapped_column(String(30),default="private");context_json:Mapped[str]=mapped_column(Text,default="{}");created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
 __table_args__=(UniqueConstraint("tenant_id","runtime_type","runtime_reference",name="uq_solution_runtime_identity"),)

class SolutionJob(Base):
 __tablename__="solution_jobs"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),nullable=False,index=True);solution_id:Mapped[str]=mapped_column(ForeignKey("solutions.id"),nullable=False,index=True);source_version_reference:Mapped[str]=mapped_column(String(120),nullable=False);job_type:Mapped[str]=mapped_column(String(30),nullable=False,index=True);status:Mapped[str]=mapped_column(String(30),nullable=False,index=True);attempt:Mapped[int]=mapped_column(Integer,default=1);queued_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);started_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True);ended_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True);log_json:Mapped[str]=mapped_column(Text,default="[]");evidence_json:Mapped[str]=mapped_column(Text,default="{}");failure_classification:Mapped[str|None]=mapped_column(String(80),nullable=True);cancellation_requested:Mapped[bool]=mapped_column(Boolean,default=False);idempotency_key:Mapped[str]=mapped_column(String(160),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
 __table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_solution_job_idempotency"),)

class SolutionDeployment(Base):
 __tablename__="solution_deployments"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),nullable=False,index=True);solution_id:Mapped[str]=mapped_column(ForeignKey("solutions.id"),nullable=False,index=True);job_id:Mapped[str]=mapped_column(ForeignKey("solution_jobs.id"),nullable=False,index=True);provider:Mapped[str]=mapped_column(String(60),nullable=False);provider_reference:Mapped[str]=mapped_column(String(200),nullable=False);version_reference:Mapped[str]=mapped_column(String(120),nullable=False);previous_deployment_id:Mapped[str|None]=mapped_column(ForeignKey("solution_deployments.id"),nullable=True);public_slug:Mapped[str]=mapped_column(String(160),nullable=False,unique=True,index=True);public_url:Mapped[str]=mapped_column(Text,nullable=False);artifact_reference:Mapped[str]=mapped_column(Text,nullable=False);artifact_digest:Mapped[str]=mapped_column(String(80),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False,index=True);health_state:Mapped[str]=mapped_column(String(30),nullable=False);health_evidence_json:Mapped[str]=mapped_column(Text,default="{}");deployed_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)

class SolutionDomain(Base):
 __tablename__="solution_domains"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),nullable=False,index=True);solution_id:Mapped[str]=mapped_column(ForeignKey("solutions.id"),nullable=False,index=True);requested_domain:Mapped[str]=mapped_column(String(253),nullable=False);verification_state:Mapped[str]=mapped_column(String(30),default="pending");dns_requirements_json:Mapped[str]=mapped_column(Text,default="{}");ssl_state:Mapped[str]=mapped_column(String(30),default="pending");created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
 __table_args__=(UniqueConstraint("tenant_id","requested_domain",name="uq_solution_requested_domain"),)

class PresenceObservation(Base):
 __tablename__="presence_observations"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),nullable=False,index=True);solution_id:Mapped[str]=mapped_column(ForeignKey("solutions.id"),nullable=False,index=True);observation_type:Mapped[str]=mapped_column(String(60),nullable=False,index=True);status:Mapped[str]=mapped_column(String(30),nullable=False,index=True);fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);evidence_json:Mapped[str]=mapped_column(Text,default="{}");observed_version_reference:Mapped[str|None]=mapped_column(String(120),nullable=True);observed_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,index=True);resolved_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True)
 __table_args__=(UniqueConstraint("tenant_id","solution_id","observation_type","fingerprint",name="uq_presence_observation_fingerprint"),)

class SolutionImprovementProposal(Base):
 __tablename__="solution_improvement_proposals"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),nullable=False,index=True);solution_id:Mapped[str]=mapped_column(ForeignKey("solutions.id"),nullable=False,index=True);observation_id:Mapped[str]=mapped_column(ForeignKey("presence_observations.id"),nullable=False,index=True);action_id:Mapped[str|None]=mapped_column(ForeignKey("business_actions.id"),nullable=True,index=True);status:Mapped[str]=mapped_column(String(30),default="proposed",index=True);issue:Mapped[str]=mapped_column(Text,nullable=False);supporting_evidence_json:Mapped[str]=mapped_column(Text,default="{}");affected_facts_json:Mapped[str]=mapped_column(Text,default="[]");affected_artifacts_json:Mapped[str]=mapped_column(Text,default="[]");proposed_change_json:Mapped[str]=mapped_column(Text,nullable=False);expected_outcome:Mapped[str]=mapped_column(Text,nullable=False);risk:Mapped[str]=mapped_column(String(30),default="medium");approval_required:Mapped[bool]=mapped_column(Boolean,default=True);before_version_reference:Mapped[str|None]=mapped_column(String(120),nullable=True);after_version_reference:Mapped[str|None]=mapped_column(String(120),nullable=True);deployment_id:Mapped[str|None]=mapped_column(ForeignKey("solution_deployments.id"),nullable=True);approved_by:Mapped[str|None]=mapped_column(String(120),nullable=True);verification_json:Mapped[str]=mapped_column(Text,default="{}");created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
