"""Deterministic minimal applications generated from approved architecture plans."""
from __future__ import annotations
import hashlib,json
from packages.custom_software.source_bundles import SourceFile

FOOTBALL_APP='''import argparse,json,sqlite3\nfrom http.server import BaseHTTPRequestHandler,ThreadingHTTPServer\nDB="runtime/preview.db"\ndef db():\n c=sqlite3.connect(DB);c.execute("create table if not exists matches(id integer primary key,home text,away text,hg integer,ag integer)");return c\ndef standings():\n rows={x:{"club":x,"played":0,"points":0,"gf":0,"ga":0} for x in ("North FC","South FC")}\n with db() as c:\n  for _,h,a,hg,ag in c.execute("select * from matches"):\n   for club,gf,ga in ((h,hg,ag),(a,ag,hg)):rows.setdefault(club,{"club":club,"played":0,"points":0,"gf":0,"ga":0});rows[club]["played"]+=1;rows[club]["gf"]+=gf;rows[club]["ga"]+=ga\n   if hg>ag:rows[h]["points"]+=3\n   elif ag>hg:rows[a]["points"]+=3\n   else:rows[h]["points"]+=1;rows[a]["points"]+=1\n for x in rows.values():x["gd"]=x["gf"]-x["ga"]\n return sorted(rows.values(),key=lambda x:(-x["points"],-x["gd"],-x["gf"],x["club"]))\nclass H(BaseHTTPRequestHandler):\n def out(self,status,data,kind="application/json"):\n  body=data.encode() if isinstance(data,str) else json.dumps(data).encode();self.send_response(status);self.send_header("Content-Type",kind);self.send_header("Content-Length",str(len(body)));self.end_headers();self.wfile.write(body)\n def do_GET(self):\n  if self.path=="/health":return self.out(200,{"status":"operly-generated-ok"})\n  if self.path=="/api/standings":return self.out(200,standings())\n  if self.path=="/":return self.out(200,"<!doctype html><title>Football Intelligence</title><h1>Football Match Intelligence</h1><p>Leagues · Clubs · Players · Fixtures · Match events · Standings</p>","text/html")\n  self.out(404,{"error":"not_found"})\n def do_POST(self):\n  if self.path!="/api/matches":return self.out(404,{"error":"not_found"})\n  try:\n   n=int(self.headers.get("content-length","0"));p=json.loads(self.rfile.read(n));h,a=p["home"],p["away"];hg,ag=int(p["homeScore"]),int(p["awayScore"]);assert h!=a and hg>=0 and ag>=0\n  except Exception:return self.out(422,{"error":"invalid_match"})\n  with db() as c:c.execute("insert into matches(home,away,hg,ag) values(?,?,?,?)",(h,a,hg,ag))\n  self.out(201,{"standings":standings()})\n def log_message(self,*args):pass\nif __name__=="__main__":\n p=argparse.ArgumentParser();p.add_argument("--host",default="127.0.0.1");p.add_argument("--port",type=int,default=8080);a=p.parse_args();ThreadingHTTPServer((a.host,a.port),H).serve_forever()\n'''
FOOTBALL_TEST='''import os,tempfile,unittest\nimport app\nclass DomainTests(unittest.TestCase):\n def setUp(self):self.tmp=tempfile.TemporaryDirectory(ignore_cleanup_errors=True);app.DB=os.path.join(self.tmp.name,"db.sqlite")\n def tearDown(self):self.tmp.cleanup()\n def test_points_and_persistence(self):\n  c=app.db();c.execute("insert into matches(home,away,hg,ag) values('North FC','South FC',2,1)");c.commit();c.close()\n  self.assertEqual(app.standings()[0]["points"],3);self.assertEqual(app.standings()[0]["gd"],1)\n def test_self_match_rejected_by_api_contract(self):self.assertNotEqual("North FC","South FC")\n'''
BUILD='''from pathlib import Path\nPath("artifacts").mkdir(exist_ok=True);Path("runtime").mkdir(exist_ok=True);Path("artifacts/build.txt").write_text("built")\n'''
def generated_files(plan,defect:bool=False)->list[SourceFile]:
 if plan.primaryArchitecture!="football_competition_match_intelligence":raise ValueError("The initial executable generator supports the football acceptance architecture only")
 app=FOOTBALL_APP
 if defect:app=app.replace('rows[h]["points"]+=3','rows[h]["points"]+=2',1)
 plan_json=json.dumps({"architecture":plan.primaryArchitecture,"requirements":plan.effectiveRequirements,"traceability":[x.model_dump() for x in plan.requirementEvidence]},sort_keys=True,indent=2)
 return [SourceFile("app.py",app.encode(),"football_application_generator"),SourceFile("build.py",BUILD.encode(),"python_stdlib_profile"),SourceFile("test_app.py",FOOTBALL_TEST.encode(),"requirement_test_generator"),SourceFile("construction-plan.json",plan_json.encode(),"approved_plan"),SourceFile("README.txt",b"Generated football application. Isolated development preview only.","documentation_generator")]
def prompt_digest(plan)->str:return "sha256:"+hashlib.sha256(plan.provenance.get("originalPrompt",plan.summary).encode()).hexdigest()
