import html,json

def data(value):return json.dumps(value,separators=(",",":")).replace("<","\\u003c")

def render_quotation_public(project):
    cfg=data({"slug":project.slug,"projectId":project.id})
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(project.name)}</title><link rel="stylesheet" href="/static/pack-runtime.css"></head><body class="quote-public"><nav><b>{html.escape(project.name)}</b><a href="#inquiry">Plan a journey</a></nav><main><section class="quote-hero" data-operly-artifact-id="public_inquiry.editorial_hero"><p>TAILORED TRAVEL, CLEARLY PRICED</p><h1>A considered itinerary, built around you.</h1><aside>01 — Tell us what matters<br>02 — Review a crafted proposal<br>03 — Refine before you commit</aside></section><section id="inquiry" class="quote-inquiry"><div><h2>Start with the shape of your trip.</h2><p>No canned packages—an agent turns your brief into a versioned quotation.</p></div><form id="quote-inquiry" data-operly-artifact-id="public_inquiry.inquiry_form"><label>Name<input name="name" required minlength="2"></label><label>Email<input name="email" type="email" required></label><label>Your trip<textarea name="requirements" required minlength="10"></textarea></label><button>Send travel brief</button><p role="status"></p></form></section></main><script id="pack-config" type="application/json">{cfg}</script><script src="/static/pack-runtime.js"></script></body></html>'''

def render_quotation_staff(project):
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quotations · {html.escape(project.name)}</title><link rel="stylesheet" href="/static/pack-runtime.css"></head><body class="quote-staff"><aside><b>{html.escape(project.name)}</b><a>Inquiry desk</a><a>Quotation editor</a><a>Manager review</a><a>Version history</a></aside><main><header><p>QUOTATION WORKSPACE</p><h1>Turn a brief into a decision-ready proposal.</h1></header><section id="quote-queue" data-operly-artifact-id="inquiry_queue.inquiry_queue"><p>Loading inquiries…</p></section></main><script id="pack-config" type="application/json">{data({'projectId':project.id,'pack':'quotation'})}</script><script src="/static/pack-runtime.js"></script></body></html>'''

def render_inventory(project):
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inventory · {html.escape(project.name)}</title><link rel="stylesheet" href="/static/pack-runtime.css"></head><body class="inventory-app"><header><div><small>STOCK CONTROL / LIVE</small><h1>{html.escape(project.name)}</h1></div><button id="new-product">+ Product</button></header><nav><a>Overview</a><a>Products</a><a>Receiving</a><a>Low stock</a><a>Purchase orders</a><a>Movement history</a></nav><main><section class="inventory-metrics"><article><b id="product-count">0</b><span>products</span></article><article><b id="low-count">0</b><span>need attention</span></article><article><b>—</b><span>open purchase orders</span></article></section><section class="inventory-grid"><div data-operly-artifact-id="inventory_dashboard.low_stock_queue"><div class="section-head"><h2>Low-stock priorities</h2><span>threshold driven</span></div><div id="low-stock"><p>No low-stock items.</p></div></div><aside><h2>Receive or adjust</h2><p>Every quantity change creates an immutable stock movement at one location.</p></aside></section></main><script id="pack-config" type="application/json">{data({'projectId':project.id,'pack':'inventory'})}</script><script src="/static/pack-runtime.js"></script></body></html>'''

def render_customer_quotation(token):
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Your quotation</title><link rel="stylesheet" href="/static/pack-runtime.css"></head><body class="quote-public"><nav><b>YOUR PROPOSAL</b></nav><main id="customer-quote" class="customer-quote" data-operly-artifact-id="customer_quotation.price_sidebar"><p>Loading quotation…</p></main><script id="pack-config" type="application/json">{data({'token':token,'pack':'customer_quotation'})}</script><script src="/static/pack-runtime.js"></script></body></html>'''
