"""Installed architecture pack declarations used for generation coverage."""
from dataclasses import dataclass
@dataclass(frozen=True)
class ArchitecturePack:
    id:str;entities:tuple[str,...];relationships:tuple[str,...];workflows:tuple[str,...];states:tuple[str,...];public_surfaces:tuple[str,...];internal_surfaces:tuple[str,...];roles:tuple[str,...];permissions:tuple[str,...];apis:tuple[str,...];renderer:str;tests:tuple[str,...];limitations:tuple[str,...];optional_dependencies:tuple[str,...]=();conflicts:tuple[str,...]=()
PACKS={
"field_service":ArchitecturePack("field_service",("customer","service_request","status_event"),("customer_has_requests",),("service_lifecycle",),("submitted","assigned","en_route","completed"),("public_request","customer_status"),("dispatch_queue",),("customer","dispatcher","technician","administrator"),("request:create","status:read","request:read","request:assign","request:transition","request:read_assigned","project:manage"),("public_request","list_requests","transition_request"),"render_field_service",("field_service_loop","tenant_isolation","idempotency"),("linear dispatch lifecycle",),("payments","messaging")),
"quotation":ArchitecturePack("quotation",("customer","inquiry","quotation","quotation_version","line_item","deliverable","approval","status_event"),("customer_has_inquiries","quotation_has_versions","version_has_lines"),("quotation_lifecycle",),("inquiry_received","quotation_draft","internal_review","approved_for_sending","sent_to_customer","revision_requested","revised","accepted","rejected"),("public_inquiry","customer_quotation"),("inquiry_queue","quotation_editor","approval_review"),("customer","agent","manager","administrator"),("inquiry:create","quotation:read_own","revision:create","inquiry:read","quotation:write","quotation:send","quotation:approve","quotation:manage"),("create_inquiry","create_quote","approve_quote","send_quote","revise_quote"),"render_quotation",("quotation_loop","approval_gate","tenant_isolation"),("payment collection is optional",),("crm","messaging","document_generation"),("field_service",)),
"inventory":ArchitecturePack("inventory",("product","supplier","inventory_location","stock_level","stock_movement","purchase_order","purchase_order_line_item","reorder_rule"),("product_has_stock","supplier_has_orders","order_has_lines"),("purchase_order_lifecycle",),("draft","approved","ordered","partially_received","received","closed"),(),("inventory_dashboard","product_catalog","receiving","low_stock","purchase_orders"),("owner","manager","stock_employee","purchasing_employee","administrator"),("inventory:all","purchase_order:approve","inventory:adjust","stock:receive","stock:adjust","purchase_order:write","inventory:admin"),("products","stock_movements","low_stock","purchase_orders","receive_order"),"render_inventory",("inventory_loop","transactionality","tenant_isolation"),("commerce checkout is optional",),("commerce",),("field_service",)),
}
def pack_manifest(pack_id:str)->dict:
    pack=PACKS[pack_id];return {name:(list(value) if isinstance(value,tuple) else value) for name,value in pack.__dict__.items()}
