import html
import json


def _data(value) -> str:
    return json.dumps(value, separators=(",", ":")).replace("<", "\\u003c")


def render_public(project, brand_override: dict | None = None) -> str:
    brand=brand_override or json.loads(project.brand_json);issues="".join(f'<option value="{html.escape(x)}">{html.escape(x)}</option>' for x in brand["issues"])
    config={"slug":project.slug,"brand":brand,"artifacts":{"hero":"public.hero","form":"public.request-form"}}
    media_class=html.escape(brand.get("heroMedia","graphic"));layout_class=html.escape(brand.get("requestLayout","section"));font_class=html.escape(brand.get("displayFont","condensed"));spacing_class=html.escape(brand.get("spacing","editorial"))
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(project.name)}</title><link rel="stylesheet" href="/static/service-project.css"></head>
<body class="font-{font_class} spacing-{spacing_class} media-{media_class} request-{layout_class}" data-vertical="{html.escape(brand['vertical'])}" style="--primary:{brand['primary']};--accent:{brand['accent']};--ink:{brand['ink']};--surface:{brand['surface']}">
<nav><a class="wordmark" href="#top"><span>///</span>{html.escape(project.name)}</a><div><a href="#services">Services</a><a href="#process">How it works</a><a class="nav-cta" href="#request">Request help</a></div></nav>
<main id="top"><section class="hero" data-operly-artifact-id="public.hero"><div class="hero-copy"><p class="eyebrow">{html.escape(brand['eyebrow'])}</p><h1>{html.escape(brand['headline'])}</h1><p class="lede">{html.escape(brand['lede'])}</p><a class="cta" href="#request">Get help now <b>→</b></a><div class="availability"><i></i><span><strong>Responders active</strong>Typical arrival 28–42 min</span></div></div><div class="hero-visual"><div class="route-line"></div><div class="dispatch-marker">R</div><div class="visual-note">LIVE RESPONSE<br><b>LOCAL CREW</b></div></div></section>
<section class="proof"><span>Background-checked crews</span><span>Clear estimates</span><span>Live status updates</span><span>Insured service</span></section>
<section id="services" class="editorial"><p class="eyebrow">Help without the guesswork</p><h2>Repair where you are.<br>Transport when you need it.</h2><div class="service-copy"><p>Tell us what happened and where you are. A dispatcher reviews every request before a qualified responder is assigned.</p><p>You'll always know the next step, who is coming, and when the situation changes.</p></div></section>
<section id="process" class="steps"><article><b>01</b><h3>Pin the problem</h3><p>Share your location and the essentials.</p></article><article><b>02</b><h3>Meet your responder</h3><p>Dispatch confirms the right crew and ETA.</p></article><article><b>03</b><h3>Get moving again</h3><p>Follow progress through completion.</p></article></section>
<section id="request" class="request-zone" data-operly-artifact-id="public.request-form"><div><p class="eyebrow">Start a request</p><h2>Where should we meet you?</h2><p>Required fields are marked. Dispatch will confirm availability after submission.</p></div><form id="service-request" novalidate><label>What happened?<select name="issue_category" required><option value="">Choose an issue</option>{issues}</select></label><label>Service location<input name="address" required minlength="5" placeholder="Street address or nearby landmark"></label><label>{html.escape(brand['asset'])}<input name="asset_details" placeholder="Optional details"></label><div class="split"><label>Your name<input name="name" required minlength="2"></label><label>Phone<input name="phone" required minlength="7" inputmode="tel"></label></div><label>Email<input name="email" type="email"></label><label>Anything else?<textarea name="description" maxlength="2000"></textarea></label><button type="submit">Send rescue request <b>→</b></button><p class="form-state" role="alert"></p></form></section>
</main><footer><span>{html.escape(project.name)}</span><p>Built for the moment plans break down.</p></footer><script id="service-config" type="application/json">{_data(config)}</script><script src="/static/service-project.js"></script></body></html>'''


def render_dispatch(project) -> str:
    config={"projectId":project.id,"slug":project.slug,"artifacts":{"queue":"dispatch.queue"}}
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dispatch · {html.escape(project.name)}</title><link rel="stylesheet" href="/static/service-project.css"></head><body class="dispatch-body"><header class="dispatch-head"><div><span class="dispatch-brand">/// {html.escape(project.name)}</span><h1>Dispatch control</h1></div><div class="system-live"><i></i> Operations live</div></header><main class="dispatch-shell" data-operly-artifact-id="dispatch.queue"><aside><p class="eyebrow">Live operations</p><strong id="open-count">0</strong><span>active requests</span><div class="legend"><i class="submitted"></i>Submitted<i class="assigned"></i>Assigned<i class="en_route"></i>En route</div></aside><section><div class="queue-head"><div><p class="eyebrow">Response queue</p><h2>Every request, one clear next move.</h2></div><button id="refresh">Refresh</button></div><div id="queue" class="queue"><p class="queue-state">Loading requests…</p></div></section></main><script id="service-config" type="application/json">{_data(config)}</script><script src="/static/service-dispatch.js"></script></body></html>'''


def render_status(project, reference: str, token: str) -> str:
    config={"slug":project.slug,"reference":reference,"token":token}
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(reference)} · {html.escape(project.name)}</title><link rel="stylesheet" href="/static/service-project.css"></head><body class="status-body"><main class="status-shell"><a class="wordmark" href="/generated/{html.escape(project.slug)}">/// {html.escape(project.name)}</a><p class="eyebrow">Rescue status</p><h1>{html.escape(reference)}</h1><div id="status-card" class="status-card"><p>Loading your latest update…</p></div></main><script id="service-config" type="application/json">{_data(config)}</script><script src="/static/service-status.js"></script></body></html>'''
