"""Managed application builder core.

Revision ID: 0003_application_builder_core
Revises: 0002_dashboard_studio
"""
from alembic import op
import sqlalchemy as sa

revision="0003_application_builder_core";down_revision="0002_dashboard_studio";branch_labels=None;depends_on=None

def upgrade():
    op.create_table("managed_applications",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("slug",sa.String(100),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("description",sa.Text(),nullable=False,server_default=""),sa.Column("active_version_id",sa.String(36),nullable=True),sa.Column("created_by",sa.String(36),sa.ForeignKey("app_users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.text("CURRENT_TIMESTAMP")),sa.UniqueConstraint("tenant_id","slug",name="uq_managed_application_slug"))
    op.create_index("ix_managed_applications_tenant_id","managed_applications",["tenant_id"])
    op.create_table("application_versions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("application_id",sa.String(36),sa.ForeignKey("managed_applications.id",ondelete="CASCADE"),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("manifest_json",sa.Text(),nullable=False),sa.Column("summary",sa.String(500),nullable=False),sa.Column("source_version_id",sa.String(36),sa.ForeignKey("application_versions.id"),nullable=True),sa.Column("created_by",sa.String(36),sa.ForeignKey("app_users.id"),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.text("CURRENT_TIMESTAMP")),sa.UniqueConstraint("application_id","version_number",name="uq_application_version_number"))
    op.create_index("ix_application_versions_tenant_id","application_versions",["tenant_id"]);op.create_index("ix_application_versions_application_id","application_versions",["application_id"]);op.create_index("ix_application_versions_active","application_versions",["active"])
    op.create_table("application_change_sets",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("application_id",sa.String(36),sa.ForeignKey("managed_applications.id",ondelete="CASCADE"),nullable=False),sa.Column("base_version_id",sa.String(36),sa.ForeignKey("application_versions.id"),nullable=False),sa.Column("request",sa.Text(),nullable=False),sa.Column("scope",sa.String(30),nullable=False),sa.Column("operations_json",sa.Text(),nullable=False),sa.Column("before_json",sa.Text(),nullable=False),sa.Column("after_json",sa.Text(),nullable=False),sa.Column("validation_json",sa.Text(),nullable=False),sa.Column("risk",sa.String(20),nullable=False,server_default="medium"),sa.Column("status",sa.String(30),nullable=False,server_default="proposed"),sa.Column("applied_version_id",sa.String(36),sa.ForeignKey("application_versions.id"),nullable=True),sa.Column("created_by",sa.String(36),sa.ForeignKey("app_users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.text("CURRENT_TIMESTAMP")))
    for col in ("tenant_id","application_id","status"):op.create_index(f"ix_application_change_sets_{col}","application_change_sets",[col])
    op.create_table("managed_records",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("application_id",sa.String(36),sa.ForeignKey("managed_applications.id",ondelete="CASCADE"),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("data_json",sa.Text(),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("app_users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.text("CURRENT_TIMESTAMP")),sa.Column("updated_at",sa.DateTime(),nullable=False,server_default=sa.text("CURRENT_TIMESTAMP")))
    for col in ("tenant_id","application_id","entity_id"):op.create_index(f"ix_managed_records_{col}","managed_records",[col])
    op.create_table("application_audit_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("application_id",sa.String(36),sa.ForeignKey("managed_applications.id",ondelete="CASCADE"),nullable=False),sa.Column("actor_id",sa.String(120),nullable=True),sa.Column("action",sa.String(80),nullable=False),sa.Column("details_json",sa.Text(),nullable=False,server_default="{}"),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.text("CURRENT_TIMESTAMP")))
    for col in ("tenant_id","application_id","action"):op.create_index(f"ix_application_audit_events_{col}","application_audit_events",[col])
    op.create_table("application_preview_sessions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("application_id",sa.String(36),sa.ForeignKey("managed_applications.id",ondelete="CASCADE"),nullable=False),sa.Column("change_set_id",sa.String(36),sa.ForeignKey("application_change_sets.id",ondelete="CASCADE"),nullable=False),sa.Column("expires_at",sa.DateTime(),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("app_users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.text("CURRENT_TIMESTAMP")))
    op.create_index("ix_application_preview_sessions_tenant_id","application_preview_sessions",["tenant_id"]);op.create_index("ix_application_preview_sessions_application_id","application_preview_sessions",["application_id"])

def downgrade():
    raise RuntimeError("Application builder downgrade is unsafe; use version rollback or restore a verified backup")
