"""solution production lifecycle
Revision ID: 0019_solution_production
Revises: 0018_solution_registry
"""
from alembic import op
import sqlalchemy as sa
revision="0019_solution_production";down_revision="0018_solution_registry";branch_labels=None;depends_on=None
def upgrade():
 tables=set(sa.inspect(op.get_bind()).get_table_names())
 if "solution_jobs" not in tables:
  op.create_table("solution_jobs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("solution_id",sa.String(36),sa.ForeignKey("solutions.id"),nullable=False),sa.Column("source_version_reference",sa.String(120),nullable=False),sa.Column("job_type",sa.String(30),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("attempt",sa.Integer(),nullable=False),sa.Column("queued_at",sa.DateTime(),nullable=False),sa.Column("started_at",sa.DateTime()),sa.Column("ended_at",sa.DateTime()),sa.Column("log_json",sa.Text(),nullable=False),sa.Column("evidence_json",sa.Text(),nullable=False),sa.Column("failure_classification",sa.String(80)),sa.Column("cancellation_requested",sa.Boolean(),nullable=False),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_solution_job_idempotency"));op.create_index("ix_solution_jobs_tenant_id","solution_jobs",["tenant_id"]);op.create_index("ix_solution_jobs_solution_id","solution_jobs",["solution_id"]);op.create_index("ix_solution_jobs_job_type","solution_jobs",["job_type"]);op.create_index("ix_solution_jobs_status","solution_jobs",["status"])
 if "solution_deployments" not in tables:
  op.create_table("solution_deployments",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("solution_id",sa.String(36),sa.ForeignKey("solutions.id"),nullable=False),sa.Column("job_id",sa.String(36),sa.ForeignKey("solution_jobs.id"),nullable=False),sa.Column("provider",sa.String(60),nullable=False),sa.Column("provider_reference",sa.String(200),nullable=False),sa.Column("version_reference",sa.String(120),nullable=False),sa.Column("previous_deployment_id",sa.String(36),sa.ForeignKey("solution_deployments.id")),sa.Column("public_slug",sa.String(160),nullable=False,unique=True),sa.Column("public_url",sa.Text(),nullable=False),sa.Column("artifact_reference",sa.Text(),nullable=False),sa.Column("artifact_digest",sa.String(80),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("health_state",sa.String(30),nullable=False),sa.Column("health_evidence_json",sa.Text(),nullable=False),sa.Column("deployed_at",sa.DateTime()),sa.Column("created_at",sa.DateTime(),nullable=False));op.create_index("ix_solution_deployments_tenant_id","solution_deployments",["tenant_id"]);op.create_index("ix_solution_deployments_solution_id","solution_deployments",["solution_id"]);op.create_index("ix_solution_deployments_job_id","solution_deployments",["job_id"]);op.create_index("ix_solution_deployments_public_slug","solution_deployments",["public_slug"],unique=True);op.create_index("ix_solution_deployments_status","solution_deployments",["status"])
 if "solution_domains" not in tables:
  op.create_table("solution_domains",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(36),sa.ForeignKey("tenants.id"),nullable=False),sa.Column("solution_id",sa.String(36),sa.ForeignKey("solutions.id"),nullable=False),sa.Column("requested_domain",sa.String(253),nullable=False),sa.Column("verification_state",sa.String(30),nullable=False),sa.Column("dns_requirements_json",sa.Text(),nullable=False),sa.Column("ssl_state",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("tenant_id","requested_domain",name="uq_solution_requested_domain"));op.create_index("ix_solution_domains_tenant_id","solution_domains",["tenant_id"]);op.create_index("ix_solution_domains_solution_id","solution_domains",["solution_id"])
def downgrade():op.drop_table("solution_domains");op.drop_table("solution_deployments");op.drop_table("solution_jobs")
