from typing import Any


MODULE_CATALOG: dict[str, dict[str, Any]] = {
    "dashboard": {
        "name": "Overview",
        "category": "core",
        "description": "Workspace health, business metrics, recent activity and quick actions.",
        "icon": "overview",
        "default_enabled": True,
        "required_permission": "workspace:read",
        "dependencies": [],
        "locked": True,
    },
    "crm": {
        "name": "CRM",
        "category": "customers",
        "description": "Contacts, leads, pipeline stages, values, ownership and follow-ups.",
        "icon": "crm",
        "default_enabled": True,
        "required_permission": "crm:read",
        "write_permission": "crm:write",
        "dependencies": [],
    },
    "catalog": {
        "name": "Products & Services",
        "category": "commerce",
        "description": "Catalog, SKUs, pricing, costs and product/service status.",
        "icon": "catalog",
        "default_enabled": True,
        "required_permission": "catalog:read",
        "write_permission": "catalog:write",
        "dependencies": [],
    },
    "inventory": {
        "name": "Inventory",
        "category": "commerce",
        "description": "Stock levels, adjustments, reorder thresholds and movement history.",
        "icon": "inventory",
        "default_enabled": True,
        "required_permission": "inventory:read",
        "write_permission": "inventory:write",
        "dependencies": ["catalog"],
    },
    "sales": {
        "name": "Sales",
        "category": "commerce",
        "description": "Orders, quotes, invoices and payment status across the customer lifecycle.",
        "icon": "sales",
        "default_enabled": True,
        "required_permission": "orders:read",
        "write_permission": "orders:write",
        "dependencies": ["crm"],
    },
    "finance": {
        "name": "Finance",
        "category": "operations",
        "description": "Invoices, expenses, revenue, costs and lightweight operating finance views.",
        "icon": "finance",
        "default_enabled": True,
        "required_permission": "finance:read",
        "write_permission": "finance:write",
        "dependencies": [],
    },
    "suppliers": {
        "name": "Suppliers & Purchasing",
        "category": "commerce",
        "description": "Vendors, purchase orders, lead times, receiving and procurement notes.",
        "icon": "suppliers",
        "default_enabled": False,
        "required_permission": "suppliers:read",
        "write_permission": "suppliers:write",
        "dependencies": ["catalog"],
    },
    "fulfillment": {
        "name": "Fulfillment",
        "category": "commerce",
        "description": "Dropship and in-house fulfillment, tracking, delivery and returns.",
        "icon": "fulfillment",
        "default_enabled": False,
        "required_permission": "fulfillment:read",
        "write_permission": "fulfillment:write",
        "dependencies": ["sales"],
    },
    "support": {
        "name": "Customer Support",
        "category": "customers",
        "description": "Customer tickets, priorities, channels, assignments and resolution status.",
        "icon": "support",
        "default_enabled": False,
        "required_permission": "support:read",
        "write_permission": "support:write",
        "dependencies": ["crm"],
    },
    "scheduling": {
        "name": "Scheduling",
        "category": "operations",
        "description": "Appointments, bookings, assignments and calendar-ready operating schedules.",
        "icon": "scheduling",
        "default_enabled": True,
        "required_permission": "appointments:read",
        "write_permission": "appointments:write",
        "dependencies": [],
    },
    "tasks": {
        "name": "Tasks",
        "category": "operations",
        "description": "Workspace tasks, ownership, due work and execution tracking.",
        "icon": "tasks",
        "default_enabled": True,
        "required_permission": "tasks:read",
        "write_permission": "tasks:write",
        "dependencies": [],
    },
    "team": {
        "name": "Team",
        "category": "operations",
        "description": "Operational staff directory plus access-controlled workspace membership.",
        "icon": "team",
        "default_enabled": True,
        "required_permission": "team:read",
        "write_permission": "team:write",
        "dependencies": [],
    },
    "documents": {
        "name": "Documents & SOPs",
        "category": "operations",
        "description": "Business notes, SOPs, policies and reusable operating documents.",
        "icon": "documents",
        "default_enabled": True,
        "required_permission": "documents:read",
        "write_permission": "documents:write",
        "dependencies": [],
    },
    "marketing": {
        "name": "Marketing",
        "category": "growth",
        "description": "Campaigns, channels, budgets, spend and attributable revenue tracking.",
        "icon": "marketing",
        "default_enabled": False,
        "required_permission": "marketing:read",
        "write_permission": "marketing:write",
        "dependencies": [],
    },
    "integrations": {
        "name": "Integrations",
        "category": "system",
        "description": "Workspace-scoped external systems, credentials, scopes and connection health.",
        "icon": "integrations",
        "default_enabled": True,
        "required_permission": "integrations:read",
        "write_permission": "integrations:manage",
        "dependencies": [],
    },
}


def module_manifest(module_key: str) -> dict[str, Any]:
    key = str(module_key or "").strip().lower()
    manifest = MODULE_CATALOG.get(key)
    if manifest is None:
        raise KeyError(f"Unknown workspace module: {module_key}")
    return {"key": key, **manifest}
